# src/MLJ/FCDW.py
#####################################################################################
# MLJ Package
#
# Functions calculating the Franck-Condon Parameters
# Author: Jolanda S Müller, Tim Rein, Imperial College London
# Copyright (c) 2025, Imperial College London, BSD 3-Clause License
# Date: November 2025
#####################################################################################

import numpy as np
from scipy.special import factorial, genlaguerre
from typing import Sequence
from MLJ.physics.config import config
from MLJ.physics.transition import TransitionType
from MLJ.physics.transition import Transition
import MLJ.physics.constants as const

def fcwd(photon_energies: Sequence[float],
         transition: Transition,
         temperatures: np.ndarray = None,
         ) -> Sequence[float]:
    """
    Compute the FCWD (Franck-Condon Weighted Density) using MLJ theory.
    For reference formula see: https://journals.aps.org/prx/pdf/10.1103/PhysRevX.8.031055 eq. 8

    Parameters
    ----------
    photon_energies : array-like
        Photon energies ω in eV.
    transition : Transition
        Transition object containing λ_o, Huang-Rhys factor S, level spacing hW,
        free energy difference E, and vibronic state dimensions.
    transition_type : str ('abs' or 'rec')
        'abs' => absorption
        'rec' => emission / recombination

    Returns
    -------
    fcwd : array, shape(N_omegas,N_disorder_energies,N_temperatures)
        FCWD evaluated at each photon energy (averaged over vibronic states).
    """

    temperatures = config.temperatures_K if temperatures is None else temperatures

    # --- Load constants and transition parameters ---
    outer_reorganisation_energy = transition.lambda_outer        # outer reorganization energy
    gibbs_energy_grid = transition.gibbs_energy_grid     # free energy difference (Array of energies if we consider disorder) (eV)
    huang_rhys = transition.huang_rhys            # Huang–Rhys factor (contains the inner reorganisation energy)
    vib_spacing = transition.state_high_energy.vib_spacing        # vibrational quantum (hΩ) (eV)
    boltzmann_eV = const.BOLTZMANN_CONSTANT_EV

    transition_type = transition.transition_type

    # Assign the number of vibrational modes to the initial and final states
    match transition_type:
        case TransitionType.ABSORPTION:
            N_vib_initial = transition.state_low_energy.number_of_vibronic_modes
            N_vib_final   = transition.state_high_energy.number_of_vibronic_modes
        case TransitionType.RECOMBINATION:
            N_vib_initial = transition.state_high_energy.number_of_vibronic_modes
            N_vib_final   = transition.state_low_energy.number_of_vibronic_modes

    v_i = np.arange(N_vib_initial + 1)
    v_f = np.arange(N_vib_final + 1)

    # Build 5D meshgrid to enable vectorization of the calculations
    v_i_mat, v_f_mat, photon_energies_mat, gibbs_energy_grid_mat, temperature_mat = np.meshgrid(
        v_i, v_f,
        photon_energies,
        gibbs_energy_grid,
        temperatures,
        indexing='ij')

    vib_diff = v_f_mat - v_i_mat

    # 2D Laguerre table (v_i × v_f)
    laguerre_base = np.zeros((N_vib_initial + 1, N_vib_final + 1))
    for i in range(N_vib_initial + 1):
        j = np.arange(i, N_vib_final + 1)
        k = j - i
        poly = [genlaguerre(i, kk)(huang_rhys) for kk in k]
        laguerre_base[i, j] = poly

    # Now broadcast to the 5D meshgrid shape
    laguerre_mat = laguerre_base[:, :, None, None, None]

    # Huang Rhys Part
    factor1 = (
        np.exp(-huang_rhys)
        * (huang_rhys ** (vib_diff))
        * factorial(v_i_mat) / factorial(v_f_mat)
        * (laguerre_mat ** 2)
    )

    # Exponential
    sign = 1 if transition_type is TransitionType.ABSORPTION else -1
    factor2 = (np.exp(
            -(-sign*photon_energies_mat + sign*gibbs_energy_grid_mat + outer_reorganisation_energy + vib_diff * vib_spacing) ** 2
            / (4 * outer_reorganisation_energy * boltzmann_eV * temperature_mat)
        ))

    # Boltzmann population of the initial state
    factor3 = np.exp(-(v_i_mat * vib_spacing) / (boltzmann_eV * temperature_mat))

    normalisation = 1 / np.sqrt(4 * np.pi * outer_reorganisation_energy * boltzmann_eV  * temperature_mat)
    fcwd_n = normalisation * factor1 * factor2 * factor3

    # Sum over v_i and v_f, as they are first and second dimension generated by np.meshgrid
    fcwd = np.sum(fcwd_n, axis=(0, 1))

    return fcwd
