# src/MLJ/FCDW.py
#####################################################################################
# MLJ Package
#
# Functions calculating the Franck-Condon Parameters
# Author: Jolanda S Müller, Tim Rein, Imperial College London
# Copyright (c) 2025, Imperial College London, BSD 3-Clause License
# Date: November 2025
#####################################################################################

import numpy as np
from scipy.special import factorial, genlaguerre
from typing import Sequence
from MLJ.physics.config import config
from MLJ.physics.transition import Transition, ProcessType
import MLJ.physics.constants as const
from MLJ.physics.basics import boltzmann, laguerre_2d

def fcwd(photon_energies: Sequence[float],
         transition: Transition,
         temperatures: np.ndarray,
         process: ProcessType,
         ) -> Sequence[float]:
    """
    Compute the FCWD (Franck-Condon Weighted Density) using MLJ theory.
    For reference formula see: https://journals.aps.org/prx/pdf/10.1103/PhysRevX.8.031055 eq. 8

    Parameters
    ----------
    photon_energies : np.ndarray
        1D array of photon energies [eV] at which to evaluate spectral rates.
    transition : Transition
       Containing states, reorganisation energies, coupling strengths, and disorder parameters.
    temperatures : np.ndarray
        1D array of temperatures [K]
    process : ProcessType
        The direction of the transition (ProcessType.ABSORPTION or ProcessType.RECOMBINATION).

    Returns
    -------
    fcwd : array, shape(N_omegas, N_disorder_energies, N_temperatures)
        FCWD evaluated at each photon energy (averaged over vibronic states).
    """

    # --- Load constants and transition parameters ---
    outer_reorganisation_energy = transition.lambda_outer        # outer reorganization energy
    gibbs_energy_grid = transition.gibbs_energy_grid     # free energy difference (Array of energies if we consider disorder) (eV)
    huang_rhys = transition.huang_rhys            # Huang–Rhys factor (contains the inner reorganisation energy)
    vib_spacing = transition.state_high_energy.vib_spacing        # vibrational quantum (hΩ) (eV)
    boltzmann_eV = const.BOLTZMANN_CONSTANT_EV

    # Assign the number of vibrational modes to the initial and final states
    match process:
        case ProcessType.ABSORPTION:
            N_vib_initial = transition.state_low_energy.number_of_vibronic_modes
            N_vib_final   = transition.state_high_energy.number_of_vibronic_modes
        case ProcessType.RECOMBINATION:
            N_vib_initial = transition.state_high_energy.number_of_vibronic_modes
            N_vib_final   = transition.state_low_energy.number_of_vibronic_modes

    v_i = np.arange(N_vib_initial + 1)
    v_f = np.arange(N_vib_final + 1)

    # 1. Define the 'Shapes' of your axes using None
    # Dimension Order: [v_i, v_f, E_phot, E_grid, Temp]
    v_i_mat     = v_i[:, None, None, None, None]               # (Ni, 1, 1, 1, 1)
    v_f_mat     = v_f[None, :, None, None, None]               # (1, Nf, 1, 1, 1)
    photon_energies_mat    = photon_energies[None, None, :, None, None]   # (1, 1, Ne, 1, 1)
    gibbs_energy_grid_mat  = gibbs_energy_grid[None, None, None, :, None] # (1, 1, 1, Ng, 1)
    temperature_mat        = temperatures[None, None, None, None, :]      # (1, 1, 1, 1, Nt)

    vib_diff = v_f_mat - v_i_mat

    # 2D Laguerre table (v_i × v_f) and broadcast to right shape
    laguerre_base = laguerre_2d(N_vib_initial, N_vib_final, huang_rhys)
    laguerre_mat = laguerre_base[:, :, None, None, None]

    # Huang Rhys Part
    factor1 = (
        np.exp(-huang_rhys)
        * (huang_rhys ** (vib_diff))
        * factorial(v_i_mat) / factorial(v_f_mat)
        * (laguerre_mat ** 2)
    )

    # Exponential
    sign = 1 if process is ProcessType.ABSORPTION else -1
    factor2 = (np.exp(
            -(-sign*photon_energies_mat + sign*gibbs_energy_grid_mat + outer_reorganisation_energy + vib_diff * vib_spacing) ** 2
            / (4 * outer_reorganisation_energy * boltzmann_eV * temperature_mat)
        ))

    # Boltzmann population of the initial state
    boltzmann_initial_vib_states = boltzmann(energy=v_i_mat * vib_spacing, temperature=temperature_mat)

    normalisation = 1 / np.sqrt(4 * np.pi * outer_reorganisation_energy * boltzmann_eV  * temperature_mat)
    fcwd_n = normalisation * factor1 * factor2 * boltzmann_initial_vib_states

    # Sum over v_i and v_f, as they are first and second dimension generated by np.meshgrid
    fcwd = np.sum(fcwd_n, axis=(0, 1))

    return fcwd
