import numpy as np
from typing import Callable
from MLJ.physics.basics import integral
from MLJ.physics.config import config

def laser_intensity_gaussian(photon_energies: np.ndarray) -> np.ndarray:
    """
    Calculate the Gaussian laser intensity profile.

    Parameters
    ----------
    photon_energies : np.ndarray
        Array of photon energies at which to evaluate the intensity, in eV.

    Returns
    -------
    np.ndarray
        The relative intensity profile. Peak intensity is centered at 
        config.laser_power with a width defined by config.laser_broadening.
    """
    return np.exp(-((photon_energies - config.laser_power) / config.laser_broadening)**2)


def excited_state_generation(
    k_abs: np.ndarray, 
    photon_energies: np.ndarray, 
    laser_intenstiy_profile_func: Callable[[np.ndarray], np.ndarray] = laser_intensity_gaussian
) -> float:
    """
    Calculate the total number of excited states generated by integrating 
    the product of the absorption rate and the laser intensity profile.

    Parameters
    ----------
    k_abs : np.ndarray
        Energy-dependent absorption rate.
    photon_energies : np.ndarray
        Energy grid in eV.
    laser_intenstiy_profile_func : Callable
        A function that accepts photon_energies and returns intensity. 
        Defaults to `laser_intensity_gaussian`.

    Returns
    -------
    float
        The integrated generation rate (area under the overlapping curves).
    """
    # Generate the intensity profile using the passed function
    laser_intensity = laser_intenstiy_profile_func(photon_energies)
    
    return integral(k_abs * laser_intensity, photon_energies)